Repository bazelbuild/rules_docker, pull requests merged in 2018-12, with the labels that each got.

#592 update groovy pin to fix e2e tests
  WORKSPACE
  container/container.bzl
Labels: cla: yes, size/M

#595 add test for container_push
  testing/e2e.sh
  tests/docker/BUILD
Labels: cla: yes, lgtm, size/S

#596 bazel_skylib: update reference to @bazel_skylib//:bzl_library.bzl
  container/BUILD
  container/container.bzl
  docker/BUILD
  skylib/BUILD
  toolchains/docker/BUILD
Labels: cla: yes, lgtm, needs-ok-to-test, size/M

#599 update readme
  README.md
  container/container.bzl
Labels: cla: yes, lgtm, size/L

#591 Add 'digest' field to PushInfo provider.
  container/providers.bzl
  container/push-tag.sh.tpl
  container/push.bzl
  tests/docker/BUILD
Labels: cla: yes, needs-ok-to-test, size/L

#602 adding --action_env=PATH to fix tests/contrib/test_compare_ids_test_* tests
  .bazelci/presubmit.yml
Labels: cla: yes, lgtm, size/S

#603 update bazel toolchains pin
  WORKSPACE
Labels: cla: yes, lgtm, size/XS

#604 Use toolchain configuration to provide an authenticated container_pull
  README.md
  container/pull.bzl
  testing/custom_toolchain_auth/WORKSPACE
  testing/default_toolchain/WORKSPACE
  testing/e2e.sh
  toolchains/docker/pull.bzl.tpl
  toolchains/docker/toolchain.bzl
Labels: cla: yes, size/L

#610 Remove x86_64 from the target constraints from the docker toolchain
  toolchains/docker/BUILD
Labels: cla: yes, lgtm, size/XS

#613 removing lots of mac targets from CI builds
  .bazelci/presubmit.yml
Labels: cla: yes, lgtm, size/S

#612 Update docs in response to #611
  README.md
Labels: cla: yes, size/XS

#619 Add test to highlight issue related to args with nodejs_image
  tests/docker/nodejs/BUILD
  tests/docker/nodejs/configs/BUILD
  tests/docker/nodejs/configs/nodejs_image.yaml
  tests/docker/nodejs/configs/nodejs_image_no_args.yaml
Labels: cla: yes, size/M

#617 add build_flags to fix rules_docker upstream CI
  .bazelci/presubmit.yml
Labels: cla: yes, size/XS

#605 Automatically infer stamping for container_{push,bundle}
  README.md
  container/bundle.bzl
  container/image_test.py
  container/push.bzl
  testdata/BUILD
  testing/e2e.sh
  tests/docker/BUILD
Labels: cla: yes, lgtm, needs-ok-to-test, size/M

#622 Do not rely on Bazel transtive loads
  WORKSPACE
  container/container.bzl
  container/image.bzl
  nodejs/image.bzl
Labels: cla: yes, lgtm, size/M

#623 Migrate out of the old action API in Bazel
  container/flatten.bzl
  container/image.bzl
  container/layer.bzl
  container/layer_tools.bzl
  container/push.bzl
  contrib/push-all.bzl
  java/image.bzl
  skylib/zip.bzl
Labels: cla: yes, lgtm, size/M

#626 Explicitly re-export functions in docker.bzl
  docker/docker.bzl
Labels: cla: yes, lgtm, size/S

#627 Update README for release 0.6.0
  README.md
Labels: cla: yes, lgtm, size/S

#629 Fix typo #628
  README.md
Labels: cla: yes, lgtm, size/XS

#631 Support '=' character in path names
  container/build_tar.py
  container/layer.bzl
  tests/docker/BUILD
  tests/docker/configs/special_characters.yaml
Labels: cla: yes, lgtm, ok-to-test, size/M

#635 Use docker path from toolchain in incremental loader
  container/layer_tools.bzl
Labels: cla: yes, lgtm, needs-ok-to-test, size/XS

#634 Use toolchains to resolve "docker" path in container_test
  contrib/test.bzl
  toolchains/docker/toolchain.bzl
Labels: cla: yes, needs-ok-to-test, size/XS

#632 Allow container_layer's data_path to work on directory output target names
  container/build_tar.py
  tests/docker/BUILD
  tests/docker/apple.bzl
  tests/docker/configs/stripped_directory_name.yaml
Labels: cla: yes, lgtm, needs-ok-to-test, size/M

#638 Fix typo in README.md
  README.md
Labels: cla: yes, lgtm, needs-ok-to-test, size/XS
