Repository bazelbuild/rules_docker, pull requests merged in 2018-11, with the labels that each got.

#565 adding new contributors
  CONTRIBUTORS
Labels: cla: yes, lgtm, size/XS

#568 Add documentation for using the docker toolchain rules
  README.md
  toolchains/docker/readme.md
Labels: cla: yes, lgtm, size/M

#569 Build more targets on RBE.
  .bazelci/presubmit.yml
Labels: cla: yes, lgtm, size/L

#570 Remove extra build/test flags.
  .bazelci/presubmit.yml
Labels: cla: yes, lgtm, size/S

#573 Remove exec constraint for docker toolchain
  toolchains/docker/BUILD
Labels: cla: yes, size/S

#576 migrate first java_image tests from image_test.py to container_test
  container/image_test.py
  tests/docker/java/BUILD
  tests/docker/java/configs/BUILD
  tests/docker/java/configs/java_image_entrypoint.yaml
Labels: cla: yes, lgtm, size/L

#563 makes java_image rule main_class parameter optional
  java/image.bzl
  testdata/BUILD
  testing/e2e.sh
  tests/docker/BUILD
  tests/docker/configs/java_entrypoint.yaml
  tests/docker/configs/java_partial_entrypoint.yaml
Labels: cla: yes, lgtm, size/M

#579 migrating more tests to tests/docker/java using container_test
  container/BUILD
  container/image_test.py
  testdata/BUILD
  testing/e2e.sh
  tests/docker/java/BUILD
  tests/docker/java/configs/java_image.yaml
  tests/docker/java/configs/java_runfiles_as_lib_image.yaml
  tests/docker/java/configs/java_runfiles_as_lib_image_entrypoint.yaml
  tests/docker/java/configs/java_runfiles_image.yaml
  tests/docker/java/configs/java_runfiles_image_entrypoint.yaml
Labels: cla: yes, lgtm, size/L

#581 Docker toolchain autoconfiguration using 'which'
  README.md
  container/container.bzl
  toolchains/docker/BUILD
  toolchains/docker/BUILD.tpl
  toolchains/docker/readme.md
  toolchains/docker/toolchain.bzl
Labels: cla: yes, lgtm, size/M

#577 added support for commas in env and labels #555
  container/BUILD
  container/image.bzl
  skylib/BUILD
  skylib/serialize.bzl
  tests/docker/BUILD
  tests/docker/configs/set_env_csv.yaml
Labels: cla: yes, lgtm, needs-ok-to-test, size/M

#587 remove unnecessary imports
  tests/docker/java/BUILD
Labels: cla: yes, lgtm, size/XS

#585 Fix not contains in end-to-end tests
  testing/e2e.sh
Labels: cla: yes, lgtm, needs-ok-to-test, size/XS

#588 extending deb test to verify workdir
  tests/docker/BUILD
  tests/docker/configs/deb_image_with_dpkgs.yaml
Labels: cla: yes, size/XS

#589 Export docker toolchain as skylark library
  docker/BUILD
  toolchains/docker/BUILD
Labels: cla: yes, lgtm, size/S

#590 replace "url" with "urls" of http_archive rule
  container/container.bzl
Labels: cla: yes, lgtm, ok-to-test, size/XS
