Repository bazelbuild/rules_docker, pull requests merged in 2019-01, with the labels that each got.

#642 Make obtainer build user in tests remote execution compatible
  container/BUILD
  container/image_test.py
  testdata/BUILD
  testdata/stamp_info.bzl
Labels: cla: yes, size/M

#639 Use incremental loader in container_test
  contrib/structure-test.sh.tpl
  contrib/test.bzl
Labels: cla: yes, lgtm, needs-ok-to-test, size/M

#636 Set path to xz in toolchain when possible
  container/build_tar.py
  container/layer.bzl
  toolchains/docker/BUILD.tpl
  toolchains/docker/toolchain.bzl
Labels: cla: yes, lgtm, needs-ok-to-test, size/S

#630 Include custom runfile symlinks in layers
  container/BUILD
  container/image_test.py
  lang/image.bzl
  testdata/BUILD
  testdata/utils.bzl
Labels: cla: yes, feature request, lgtm, needs-ok-to-test, size/M

#647 container_pull: don't drop name in returned arguments
  container/pull.bzl
Labels: cla: yes, lgtm, needs-ok-to-test, size/XS

#654 fix typo + fix CI
  .bazelci/presubmit.yml
  WORKSPACE
  container/layer.bzl
  toolchains/docker/toolchain.bzl
Labels: cla: yes, lgtm, size/M

#651 Fix container bundle pusher broken by #591
  contrib/push-all.bzl
  testing/e2e.sh
  tests/docker/BUILD
Labels: cla: yes, lgtm, size/M

#644 Migrate more tests to tests/docker
  container/BUILD
  container/image_test.py
  testdata/BUILD
  testing/e2e.sh
  tests/docker/cc/BUILD
  tests/docker/cc/configs/BUILD
  tests/docker/cc/configs/cc_image.yaml
  tests/docker/go/BUILD
  tests/docker/go/configs/BUILD
  tests/docker/go/configs/go_image.yaml
  tests/docker/groovy/BUILD
  tests/docker/groovy/configs/BUILD
  tests/docker/groovy/configs/groovy_image.yaml
  tests/docker/java/BUILD
  tests/docker/java/configs/java_partial_entrypoint.yaml
  tests/docker/java/configs/java_runfiles_image.yaml
  tests/docker/java/configs/simple_java_entrypoint.yaml
  tests/docker/python/BUILD
  tests/docker/python/configs/BUILD
  tests/docker/python/configs/py_image.yaml
  tests/docker/python3/BUILD
  tests/docker/python3/configs/BUILD
  tests/docker/python3/configs/py3_image.yaml
  tests/docker/rust/BUILD
  tests/docker/rust/configs/BUILD
  tests/docker/rust/configs/rust_image.yaml
  tests/docker/scala/BUILD
  tests/docker/scala/configs/BUILD
  tests/docker/scala/configs/scala_image.yaml
Labels: cla: yes, size/XL

#648 Fix Bazel incompatible issues.
  .bazelci/presubmit.yml
  WORKSPACE
  container/container.bzl
  container/image.bzl
  container/image_test.py
  container/layer.bzl
  container/layer_tools.bzl
  contrib/compare_ids_test.bzl
  contrib/idd.bzl
  contrib/push-all.bzl
  contrib/test.bzl
  java/image.bzl
  lang/image.bzl
  nodejs/image.bzl
  skylib/zip.bzl
  tests/contrib/compare_ids_fail_test.bzl
  tests/docker/groovy/configs/groovy_image.yaml
  tests/docker/java/configs/java_image.yaml
  tests/docker/java/configs/java_partial_entrypoint.yaml
  tests/docker/java/configs/simple_java_entrypoint.yaml
  tests/docker/scala/configs/scala_image.yaml
Labels: cla: yes, size/L

#657 Remove an unused variable.
  java/image.bzl
Labels: cla: yes, lgtm, size/XS

#658 Fix a lint issue.
  testdata/BUILD
Labels: cla: yes, lgtm, size/XS

#652 Convert dict.items() calls to use dicts.add.
  README.md
  WORKSPACE
  cc/image.bzl
  container/bundle.bzl
  container/container.bzl
  container/flatten.bzl
  container/image.bzl
  container/import.bzl
  container/layer.bzl
  container/push.bzl
  docker/docker.bzl
  go/image.bzl
  java/image.bzl
  lang/image.bzl
  nodejs/image.bzl
  python/image.bzl
  python3/image.bzl
  repositories/BUILD
  repositories/repositories.bzl
  testing/custom_toolchain_auth/WORKSPACE
  testing/default_toolchain/WORKSPACE
  testing/e2e.sh
Labels: cla: yes, size/XL

#662 Do not add --all_incompatible_changes to presubmit
  .bazelci/presubmit.yml
Labels: bug, cla: yes, lgtm

#663 Update README.md for v0.7.0 release.
  README.md
Labels: cla: yes, size/XS

#667 exec docker run statement.
  container/incremental_load.sh.tpl
Labels: cla: yes, lgtm, needs-ok-to-test, size/XS

#666 Pipe through testonly to allow building tests as an image.
  cc/image.bzl
  d/image.bzl
  go/image.bzl
  groovy/image.bzl
  java/image.bzl
  nodejs/image.bzl
  python/image.bzl
  python3/image.bzl
  rust/image.bzl
  scala/image.bzl
Labels: cla: yes, needs-ok-to-test, size/S

#655 Attempt to use `python2` first
  container/pull.bzl
Labels: cla: yes, lgtm, needs-ok-to-test, size/XS

#669 go_image() now respects restricted_to and compatible_with
  go/image.bzl
Labels: cla: yes, lgtm, needs-ok-to-test, size/XS

#672 Expand make variables in env field
  .bazelci/presubmit.yml
  container/image.bzl
  testdata/BUILD
  tests/docker/BUILD
  tests/docker/configs/set_env_make_vars.yaml
Labels: cla: yes, lgtm, needs-ok-to-test, size/M

#677 Split py_binary into py_binary and py_library …
  container/BUILD
  contrib/BUILD
  tests/container/BUILD
Labels: cla: yes, lgtm, size/S

#674 Update container_bundle doc to remark deprecation of "stamp" attribute
  README.md
Labels: cla: yes, needs-ok-to-test, size/XS

#678 Update README.md
  README.md
Labels: cla: yes, size/XS

#679 Create CODEOWNERS
  CODEOWNERS
Labels: cla: yes, size/XS
