Repository bazelbuild/rules_docker, pull requests merged in 2019-11, with the labels that each got.

#1260 Format README to sync with internal repo
  README.md
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/S

#1261 Make config stripper handle image tarballs with symlinked layers
  docker/util/BUILD
  docker/util/config_stripper.py
  docker/util/config_stripper_test.py
  docker/util/testdata/BUILD
  docker/util/testdata/image_with_symlinked_layer.tar
Labels: approved, cla: yes, lgtm, size/M

#1262 Dont assume docker path in image util
  docker/package_managers/install_pkgs.bzl
  docker/util/BUILD
  docker/util/image_util.sh.tpl
  docker/util/run.bzl
Labels: approved, cla: yes, lgtm, size/M

#1271 config_stripper no longer stores full file in RAM.
  docker/util/config_stripper.py
Labels: approved, cla: yes, lgtm, size/L

#1276 Replace merge_dicts with dicts.add
  WORKSPACE
Labels: approved, cla: yes, lgtm, size/S

#1274 added support for user defined tags on generated `container_import` r…
  container/pull.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1288 Deprecate the Kaniko tool to build images from Dockerfile
  WORKSPACE
  contrib/dockerfile_build.bzl
  contrib/kaniko_run_and_extract.sh.tpl
  tests/contrib/BUILD
Labels: approved, cla: yes, lgtm, size/L

#1277 install_pkgs uses named volumes to work with DIND.
  docker/package_managers/installer.sh.tpl
  docker/package_managers/run_install.sh.tpl
Labels: approved, cla: yes, lgtm, size/M

#1289 Update rules_python commit hash to 9467740
  container/image_test.py
  repositories/repositories.bzl
Labels: approved, cla: yes, lgtm, size/M

#1290 Move tests that use 'docker' to GCB
  .bazelci/presubmit.yml
  .bazelrc
  cloudbuild.yaml
  tests/container/cloudbuild.yaml
  tests/contrib/cloudbuild.yaml
  tests/docker/cloudbuild.yaml
Labels: approved, cla: yes, lgtm, size/L

#1298 Sync with internal change
  testdata/BUILD
Labels: approved, cla: yes, lgtm, size/XS

#1291 Fix ordering of docker entrypoint and entrypoint prefix
  container/go/pkg/compat/config.go
  container/go/pkg/compat/config_test.go
Labels: cla: yes, lgtm, size/M

#1299 move python modules out of bzl file
  WORKSPACE
  repositories/repositories.bzl
Labels: approved, cla: yes, lgtm, size/L

#1301 Sync with internal change
  testdata/BUILD
Labels: approved, cla: yes, lgtm, size/XS
