Repository bazelbuild/rules_docker, pull requests merged in 2019-09, with the labels that each got.

#1118 Make pusher & digester backwards compatible.
  container/go/cmd/digester/BUILD
  container/go/cmd/digester/digester.go
  container/go/cmd/pusher/BUILD
  container/go/cmd/pusher/pusher.go
  container/go/pkg/compat/BUILD
  container/go/pkg/oci/BUILD
  container/go/pkg/oci/image.go
  container/go/pkg/utils/BUILD
  container/go/pkg/utils/utils.go
  container/new_push.bzl
  testing/e2e.sh
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/XL

#1122 Implement a container flattener in Go
  container/BUILD
  container/flatten.bzl
  container/go/cmd/flattener/BUILD
  container/go/cmd/flattener/flattener.go
  container/image_test.py
  contrib/dockerfile_build.bzl
  testdata/BUILD
Labels: approved, cla: yes, lgtm, size/L

#1124 new_pull: expose puller_darwin and _linux attr for testing
  container/new_pull.bzl
Labels: approved, cla: yes, lgtm, size/S

#1128 Refactor puller & loader to directly generate legacy format.
  container/go/cmd/digester/digester.go
  container/go/cmd/loader/BUILD
  container/go/cmd/loader/loader.go
  container/go/cmd/puller/BUILD
  container/go/cmd/puller/puller.go
  container/go/pkg/compat/BUILD
  container/go/pkg/compat/ociToLegacy.go
  container/go/pkg/compat/write.go
Labels: approved, cla: yes, lgtm, size/L

#1123 Refactor image reader used in Go binaries fixing foreign layer, tarball loading and avoiding digest recomputation
  container/BUILD
  container/flatten.bzl
  container/go/cmd/digester/digester.go
  container/go/cmd/extract_config/extractConfig.go
  container/go/cmd/flattener/BUILD
  container/go/cmd/flattener/flattener.go
  container/go/cmd/join_layers/BUILD
  container/go/cmd/join_layers/join_layers.go
  container/go/cmd/pusher/pusher.go
  container/go/pkg/compat/BUILD
  container/go/pkg/compat/generateManifest.go
  container/go/pkg/compat/image.go
  container/go/pkg/compat/reader.go
  container/go/pkg/utils/BUILD
  container/go/pkg/utils/utils.go
  container/image_test.py
  container/layer_tools.bzl
  container/new_push.bzl
  testdata/BUILD
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/XXL

#1129 Use the new puller binaries & deprecate format attribute in puller
  .bazelci/presubmit.yml
  README.md
  WORKSPACE
  container/go/cmd/puller/puller.go
  container/new_load.bzl
  container/new_pull.bzl
  repositories/repositories.bzl
  testing/e2e.sh
  tests/container/BUILD
  tests/container/empty_layers.bzl
Labels: approved, cla: yes, lgtm, size/L

#1131 Update go-containerregistry to pull in tarball foreign layer support
  container/BUILD
  container/go/cmd/join_layers/join_layers.go
  container/image_test.py
  repositories/go_repositories.bzl
Labels: approved, cla: yes, lgtm, size/M

#1132 Simplify image non repro test
  .bazelci/presubmit.yml
  tests/contrib/BUILD
  tests/contrib/repro_imgs.yaml
Labels: approved, cla: yes, size/S

#1137 Update go-containerregistry that reverts API breaking change
  container/go/cmd/join_layers/join_layers.go
  repositories/go_repositories.bzl
Labels: approved, cla: yes, lgtm, size/M

#1138 Update readme for release v0.10.0
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1140 Switch container_pull & container_load to Go implementation
  .bazelci/presubmit.yml
  README.md
  WORKSPACE
  container/legacy_load.bzl
  container/legacy_pull.bzl
  container/load.bzl
  container/pull.bzl
  testing/e2e.sh
  testing/e2e/top_level.sh
  testing/examples/WORKSPACE
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/XL

#1141 use gcp-runtimes image in security check test
  tests/docker/security/BUILD
Labels: approved, cla: yes, lgtm, size/XS

#1147 Implement Get function for struct of type Value
  contrib/go/cmd/metadata_merge/metadata_merge.go
Labels: approved, cla: yes, lgtm, size/XS

#1149 Update README for release v0.10.1
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1148 Port fixes to image config creator discovered in #1142
  container/go/cmd/create_image_config/BUILD
  container/go/cmd/create_image_config/create_image_config.go
  container/go/cmd/extract_config/BUILD
  container/go/cmd/extract_config/extract_config.go
  container/go/pkg/compat/BUILD
  container/go/pkg/compat/config.go
  container/go/pkg/compat/config_test.go
  repositories/go_repositories.bzl
Labels: approved, cla: yes, lgtm, size/L

#1146 remove some unnecessary calls to depset.to_list()
  docker/package_managers/download_pkgs.bzl
  docker/toolchain_container/debian_pkg_tar.bzl
  docker/toolchain_container/toolchain_container.bzl
Labels: approved, cla: yes, lgtm, size/M

#1152 More performance fixes
  lang/image.bzl
Labels: approved, cla: yes, lgtm, size/S

#1153 update pin to base images docker and bazel-toolchains
  WORKSPACE
  testing/download_pkgs_at_root/WORKSPACE
Labels: approved, cla: yes, lgtm, size/M

#1156 use ctx.args in image.bzl
  container/image.bzl
Labels: approved, cla: yes, lgtm, size/L

#1157 more use ctx.args
  container/flatten.bzl
  container/image.bzl
  container/layer.bzl
  container/layer_tools.bzl
  container/new_push.bzl
  docker/package_managers/install_pkgs.bzl
Labels: approved, cla: yes, size/L

#1158 Revert "more use ctx.args"
  container/flatten.bzl
  container/image.bzl
  container/layer.bzl
  container/layer_tools.bzl
  container/new_push.bzl
  docker/package_managers/install_pkgs.bzl
Labels: approved, cla: yes, lgtm, size/L

#1159 More use ctx args
  container/flatten.bzl
  container/image.bzl
  container/layer.bzl
  container/layer_tools.bzl
  container/new_push.bzl
  docker/package_managers/install_pkgs.bzl
Labels: approved, cla: yes, lgtm, size/L

#1160 continue migrating to use of ctx.actions.args
  contrib/automatic_container_release/metadata_merge.bzl
  contrib/automatic_container_release/packages_metadata.bzl
  contrib/passwd.bzl
  docker/security/security_check.bzl
Labels: approved, cla: yes, size/M

#1161 Update README.md to remove unnecessary part of instruction.
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1162 Generate v1 image tarballs in Go join_layers
  container/go/cmd/join_layers/BUILD
  container/go/cmd/join_layers/join_layers.go
  container/go/pkg/compat/BUILD
  container/go/pkg/compat/image.go
  repositories/go_repositories.bzl
Labels: approved, cla: yes, lgtm, size/S

#1166 fix json print command for py3
  docker/util/to_json.py
Labels: approved, cla: yes, lgtm, size/XS

#1169 Remove max permsize which is not recommended for JDK 11
  testdata/BUILD
  tests/container/java/BUILD
  tests/container/java/configs/java_image.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1142 Use Go impl instead of python in all remaining container rules
  README.md
  container/flatten.bzl
  container/go/cmd/create_image_config/BUILD
  container/image.bzl
  container/image_test.py
  container/layer_tools.bzl
  container/legacy_push.bzl
  container/push.bzl
  contrib/push-all.bzl
  testing/e2e.sh
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/XL

#1171 Sync in go-containerregistry update & update test digests
  container/image_test.py
  repositories/go_repositories.bzl
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/M
