Repository bazelbuild/rules_docker, pull requests merged in 2019-07, with the labels that each got.

#949 Add bzl_library for lang/image.bzl
  lang/BUILD
Labels: approved, cla: yes, lgtm, size/S

#953 Update README.md
  README.md
Labels: approved, cla: yes, lgtm, size/S

#946 Add symlink to puller's OCI intermediate format
  container/go/cmd/puller/BUILD
  container/go/cmd/puller/puller.go
  container/go/pkg/compat/BUILD
  container/go/pkg/compat/ociToLegacy.go
Labels: approved, cla: yes, lgtm, size/L

#951 Add symlink and new file structure to loader.go binary
  container/go/cmd/loader/BUILD
  container/go/cmd/loader/loader.go
  container/go/pkg/compat/ociToLegacy.go
Labels: approved, cla: yes, lgtm, size/S

#958 Refactor puller binary to be compatible with container_import
  container/go/cmd/puller/puller.go
Labels: approved, cla: yes, lgtm, size/S

#960 Update new puller binary
  container/go/cmd/puller/puller.go
Labels: approved, cla: yes, lgtm, size/XS

#948 Add container_tests for puller and Update load and pull rules to comply with updates in #946
  WORKSPACE
  container/go/pkg/oci/BUILD
  container/new_load.bzl
  container/new_pull.bzl
  repositories/repositories.bzl
  testdata/BUILD
  testing/examples/WORKSPACE
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/L

#954 Implement new interface for legacy intermediate format layouts
  container/go/cmd/pusher/BUILD
  container/go/cmd/pusher/pusher.go
  container/go/pkg/compat/BUILD
  container/go/pkg/compat/image.go
  container/go/pkg/compat/path.go
  container/go/pkg/compat/reader.go
  container/new_push.bzl
Labels: approved, cla: yes, lgtm, size/L

#965 Add DO_NOT_IMPORT blocks to make copybara transformation easier.
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/L

#966 Added more e2e tests for new_container_push to account for legacy format
  container/go/pkg/compat/BUILD
  container/go/pkg/compat/testdata/test_index1/000.sha256
  container/go/pkg/compat/testdata/test_index1/000.tar.gz
  container/go/pkg/compat/testdata/test_index1/001.sha256
  container/go/pkg/compat/testdata/test_index1/001.tar.gz
  container/go/pkg/compat/testdata/test_index1/002.sha256
  container/go/pkg/compat/testdata/test_index1/002.tar.gz
  container/go/pkg/compat/testdata/test_index1/BUILD
  container/go/pkg/compat/testdata/test_index1/config.json
  container/go/pkg/compat/testdata/test_index1/digest
  container/go/pkg/compat/testdata/test_index1/manifest.json
  container/pull.bzl
  testing/e2e.sh
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/L

#967 Implement extractConfig binary in Go
  container/go/cmd/extract_config/BUILD
  container/go/cmd/extract_config/extractConfig.go
  container/go/cmd/extract_config/main.go
  container/layer_tools.bzl
Labels: approved, cla: yes, lgtm, size/L

#971 Release Darwin binaries for puller and loader.
  container/go/cloudbuild.yaml
  repositories/repositories.bzl
  testing/e2e/top_level.sh
Labels: approved, cla: yes, lgtm, size/M

#975 Enable using Darwin binary.
  .bazelci/presubmit.yml
  container/new_load.bzl
  container/new_pull.bzl
  repositories/repositories.bzl
Labels: approved, cla: yes, lgtm, size/M

#972 Fix error message in pusher
  container/go/cmd/pusher/pusher.go
Labels: approved, cla: yes, do-not-merge/hold, size/XS

#955 container_repro_test rule to test for container reproducibility
  .bazelci/presubmit.yml
  BUILD
  WORKSPACE
  contrib/BUILD
  contrib/cmp_images.sh.tpl
  contrib/repro_test.bzl
  repositories/deps.bzl
  repositories/images.bzl
  repositories/repositories.bzl
  tests/contrib/BUILD
Labels: approved, cla: yes, lgtm, size/L

#980 Pin containers that are used for digest tests.
  WORKSPACE
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/M

#981 Migrate toolchain_container rules to rules_docker
  .bazelci/presubmit.yml
  WORKSPACE
  docker/toolchain_container/BUILD
  docker/toolchain_container/README.md
  docker/toolchain_container/debian_pkg_tar.bzl
  docker/toolchain_container/toolchain_container.bzl
  tests/docker/toolchain_container/BUILD
  tests/docker/toolchain_container/tests.yaml
Labels: approved, cla: yes, lgtm, size/XL

#982 turn on more mac tests
  .bazelci/presubmit.yml
Labels: approved, cla: yes, lgtm, size/S

#983 Fix a typo in toolchain_container's README
  docker/toolchain_container/README.md
Labels: approved, cla: yes, lgtm, size/XS

#994 Fix a couple of issues that made new security_check different
  docker/security/security_check.py
  tests/docker/security/BUILD
Labels: approved, cla: yes, lgtm, size/XS

#988 Adjust to OutputGroupInfo
  container/bundle.bzl
Labels: approved, cla: yes, lgtm, size/S

#995 update rules scala and fix test
  WORKSPACE
  tests/container/scala/configs/scala_image.yaml
Labels: approved, cla: yes, lgtm, size/XS

#974 Refactor new_container_pull to generate fully backward compatible format
  container/go/cmd/puller/puller.go
  container/go/pkg/compat/BUILD
  container/go/pkg/compat/ociToLegacy.go
Labels: approved, cla: yes, lgtm, size/M

#1000 Remove required node_modules arg and layers
  nodejs/image.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1002 Fix python use in new docker/... rules
  contrib/repro_test.bzl
  docker/package_managers/download_pkgs.bzl
  docker/package_managers/install_pkgs.bzl
  docker/package_managers/run_download.sh.tpl
  docker/package_managers/run_install.sh.tpl
  docker/toolchain_container/debian_pkg_tar.bzl
  docker/util/commit.sh.tpl
  docker/util/extract.sh.tpl
  docker/util/run.bzl
Labels: approved, cla: yes, lgtm, size/M

#1003 Test container repro test in gcb
  .bazelci/presubmit.yml
  contrib/cmp_images.sh.tpl
  contrib/repro_test.bzl
  docker/util/run.bzl
  tests/contrib/BUILD
  tests/contrib/mv_project_root.sh
  tests/contrib/repro_imgs.yaml
  tests/docker/toolchain_container/BUILD
Labels: approved, cla: yes, lgtm, size/L

#1006 Allow testing for image non-determinism
  .bazelci/presubmit.yml
  contrib/cmp_images.sh.tpl
  contrib/repro_test.bzl
  tests/contrib/BUILD
  tests/contrib/repro_imgs.yaml
Labels: approved, cla: yes, lgtm, size/M

#999 Update new pusher to consume container_image output
  container/go/cmd/pusher/pusher.go
  container/go/pkg/compat/BUILD
  container/go/pkg/compat/generateManifest.go
  container/go/pkg/compat/image.go
  container/go/pkg/compat/path.go
  container/go/pkg/compat/reader.go
  container/go/pkg/compat/testdata/test_index1/0.sha256
  container/go/pkg/compat/testdata/test_index1/0.tar.gz
  container/go/pkg/compat/testdata/test_index1/1.sha256
  container/go/pkg/compat/testdata/test_index1/1.tar.gz
  container/go/pkg/compat/testdata/test_index1/2.sha256
  container/go/pkg/compat/testdata/test_index1/2.tar.gz
  container/new_push.bzl
  container/utils.bzl
  testing/e2e.sh
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/L

#1011 Add e2e tests to check new_pusher compatibility
  .bazelci/presubmit.yml
  container/new_pull.bzl
  testdata/BUILD
  testdata/go_pusher_test.tar
  testing/e2e.sh
  testing/new_pusher_tests/BUILD
  testing/new_pusher_tests/WORKSPACE
  tests/container/BUILD
  tests/container/configs/verify_new_pusher.yaml
Labels: approved, cla: yes, lgtm, size/L

#1017 Add a test rule to syntax check file update & dependency update spec
  .bazelci/presubmit.yml
  contrib/automatic_container_release/BUILD
  contrib/automatic_container_release/run_checker.sh.tpl
  contrib/automatic_container_release/syntax/BUILD
  contrib/automatic_container_release/syntax/dependency_update.bzl
  contrib/automatic_container_release/syntax/file_update.bzl
  tests/contrib/automatic_container_release/syntax/BUILD
  tests/contrib/automatic_container_release/syntax/deps_spec.yaml
  tests/contrib/automatic_container_release/syntax/file_updates.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1018 Add method needed for internal go flags implementation
  container/go/cmd/pusher/pusher.go
Labels: approved, cla: yes, lgtm, size/XS

#1021 remove note about Windows support
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1025 Replace syntax checker with single tester for configs.
  contrib/automatic_container_release/configs_test.bzl
  contrib/automatic_container_release/run_checker.sh.tpl
  contrib/automatic_container_release/syntax/dependency_update.bzl
  contrib/automatic_container_release/syntax/file_update.bzl
  tests/contrib/automatic_container_release/BUILD
  tests/contrib/automatic_container_release/deps_spec.yaml
  tests/contrib/automatic_container_release/file_updates.yaml
  tests/contrib/automatic_container_release/syntax/BUILD
Labels: approved, cla: yes, lgtm, size/L

#1034 Specifying a file update or dep spec YAML is optional to configs_test
  contrib/automatic_container_release/configs_test.bzl
  tests/contrib/automatic_container_release/BUILD
Labels: approved, cla: yes, lgtm, size/S

#1027 docker/util: adding arg docker_run_flags to container_run_and_commit
  docker/util/README.md
  docker/util/commit.sh.tpl
  docker/util/run.bzl
  tests/docker/util/BUILD
Labels: approved, cla: yes, lgtm, size/S

#1036 Fix rules_python workspace name
  WORKSPACE
  repositories/py_repositories.bzl
  repositories/repositories.bzl
Labels: approved, cla: yes, lgtm, size/S

#1039 Changed pusher default format to legacy
  container/new_push.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1040 Move basic image repro tests to GCB
  .bazelci/presubmit.yml
  tests/contrib/repro_imgs.yaml
Labels: approved, cla: yes, lgtm, size/S

#1041 Update README with instructions for release v0.9.0
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1043 Change new pusher tests path
  testing/new_pusher_tests/BUILD
  testing/new_pusher_tests/WORKSPACE
Labels: approved, cla: yes, lgtm, size/XS
