Repository bazelbuild/rules_docker, pull requests merged in 2019-03, with the labels that each got.

#702 Run update_deps.sh to update latest security fixes from distroless.
  cc/cc.bzl
  go/go.bzl
  java/java.bzl
  java/jetty.bzl
  nodejs/nodejs.bzl
  python/python.bzl
  python3/python3.bzl
Labels: cla: yes, lgtm, needs-ok-to-test, size/M

#691 container_push: added attribute 'tag_file'
  container/push.bzl
  testing/e2e.sh
  tests/docker/BUILD
Labels: cla: yes, lgtm, needs-ok-to-test, size/M

#710 Fix buildifier 0.22.0 warnings in files matching *image.bzl
  .bazelci/presubmit.yml
  cc/image.bzl
  container/BUILD
  container/image.bzl
  contrib/BUILD
  contrib/rename_image.bzl
  d/image.bzl
  go/image.bzl
  groovy/image.bzl
  java/image.bzl
  lang/image.bzl
  nodejs/image.bzl
  python/image.bzl
  python3/image.bzl
  rust/image.bzl
  scala/image.bzl
  tests/docker/BUILD
  tools/BUILD
Labels: cla: yes, lgtm, size/L

#708 Update CODEOWNERS
  CODEOWNERS
Labels: cla: yes, lgtm, size/XS

#706 Containerregistry cached
  README.md
  container/pull.bzl
  repositories/repositories.bzl
  testing/e2e.sh
Labels: cla: no, size/M

#697 Forward new provider for python in filter_layer
  lang/image.bzl
Labels: cla: yes, lgtm, needs-ok-to-test, size/M

#707 update bazel-toolchains and add rbe_autoconfig target
  .bazelci/presubmit.yml
  WORKSPACE
Labels: cla: yes, lgtm, size/M

#709 adding docstrings
  .bazelci/presubmit.yml
  .travis.yml
  cc/cc.bzl
  cc/image.bzl
  container/bundle.bzl
  container/layer.bzl
  container/layer_tools.bzl
  container/pull.bzl
  contrib/BUILD
  contrib/group.bzl
  contrib/passwd.bzl
  contrib/rename_image.bzl
  contrib/test.bzl
  contrib/with-tag.bzl
  go/go.bzl
  go/image.bzl
  java/image.bzl
  java/java.bzl
  java/jetty.bzl
  nodejs/image.bzl
  nodejs/nodejs.bzl
  python/image.bzl
  python/python.bzl
  python3/image.bzl
  python3/python3.bzl
  skylib/label.bzl
  skylib/path.bzl
  testdata/BUILD
  testdata/pause_piecemeal/layers.bzl
  tests/docker/apple.bzl
  tools/update_deps.py
Labels: cla: yes, size/L

#712 Fix Bazel incompatible issues.
  WORKSPACE
  java/image.bzl
Labels: cla: yes, lgtm, size/XS

#711 Publish an image.digest file for container_pull.
  container/pull.bzl
  tests/docker/BUILD
Labels: cla: yes, lgtm, needs-ok-to-test, size/S

#715 use rbe_autoconfig platform
  .bazelci/presubmit.yml
  WORKSPACE
  toolchains/BUILD
Labels: cla: yes, lgtm, size/M

#716 Fix attribute type for inputs.
  container/image.bzl
Labels: cla: yes, size/XS

#726 Run renovate once daily instead of all the time
  renovate.json
Labels: cla: yes, lgtm, size/XS

#727 Revert "use rbe_autoconfig platform"
  .bazelci/presubmit.yml
  WORKSPACE
  toolchains/BUILD
Labels: cla: yes, lgtm, size/M

#729 Update subpar dependency
  repositories/repositories.bzl
Labels: cla: yes, lgtm, size/XS

#713 Re-enable buildifier on buildkite
  .bazelci/presubmit.yml
  .travis.yml
Labels: cla: yes, size/S

#730 Go image doc update
  README.md
Labels: cla: yes, lgtm, size/XS

#724 Cleanups
  WORKSPACE
  container/push.bzl
  contrib/compare_ids_test.bzl
  contrib/push-all.bzl
  contrib/test.bzl
  java/image.bzl
  lang/image.bzl
  nodejs/image.bzl
  tests/contrib/BUILD
  tests/contrib/compare_ids_fail_test.bzl
Labels: cla: yes, lgtm, needs-ok-to-test, size/M

#733 Use a single url in the "urls" field for bazel-toolchains
  WORKSPACE
Labels: cla: yes, lgtm, size/XS

#734 Fail when pulled image with unexpected sha256
  WORKSPACE
  container/pull.bzl
  tests/docker/BUILD
Labels: cla: yes, size/S

#701 nodejs_image: Allow passing in custom binary.
  nodejs/image.bzl
  tests/docker/nodejs/BUILD
  tests/docker/nodejs/configs/nodejs_image_custom_binary.yaml
  tests/docker/nodejs/configs/nodejs_image_custom_binary_with_args.yaml
Labels: cla: yes, needs-ok-to-test, size/M

#731 Add error message when docker is not available in incremental loader
  container/incremental_load.sh.tpl
Labels: cla: yes, needs-ok-to-test, size/XS

#737 Repo rule to build an image from Dockerfile and save as tar
  .bazelci/presubmit.yml
  WORKSPACE
  contrib/Dockerfile
  contrib/dockerfile_build.bzl
  testing/e2e.sh
  tests/docker/BUILD
  tests/docker/configs/basic_dockerfile.yaml
Labels: cla: yes, size/L

#744 Remove unused imports for legacy image formats.
  container/join_layers.py
Labels: cla: yes, lgtm, size/XS

#740 Basic Dockerfile vs container_image example
  .bazelci/presubmit.yml
  testing/examples/README.md
  testing/examples/WORKSPACE
  testing/examples/basic/BUILD
  testing/examples/basic/Dockerfile
  testing/examples/basic/test_configs/BUILD
  testing/examples/basic/test_configs/basic_alpine.yaml
Labels: cla: yes, size/L

#743 Add note on how to obtain a correct digest
  README.md
Labels: cla: yes, needs-ok-to-test, size/XS

#748 Use the supplied Dockerfile for docker build command
  contrib/dockerfile_build.bzl
Labels: cla: yes, lgtm, size/S

#749 Extended dockerfile example
  testing/examples/WORKSPACE
  testing/examples/basic/BUILD
  testing/examples/extended/BUILD
  testing/examples/extended/Dockerfile
  testing/examples/extended/image_data/BUILD
  testing/examples/extended/image_data/Data_file.txt
  testing/examples/extended/image_data/More_data.txt
  testing/examples/extended/image_data/file_to_copy.txt
  testing/examples/extended/image_data/tarfile.tar
  testing/examples/extended/test_configs/BUILD
  testing/examples/extended/test_configs/extended_alpine.yaml
Labels: cla: yes, size/L

#747 Create empty workspace directory to fix using python deps as layers
  container/image_test.py
  java/image.bzl
  lang/image.bzl
  nodejs/image.bzl
  python/image.bzl
  testdata/test/BUILD
  testdata/test/py_image_using_layers.py
  testing/e2e.sh
Labels: cla: yes, lgtm, size/M

#759 Update httplib2 to v0.12.1
  repositories/repositories.bzl
Labels: cla: yes, lgtm, size/XS

#750 Add dockerfile example that uses the RUN instruction
  testing/examples/WORKSPACE
  testing/examples/run_instruction/BUILD
  testing/examples/run_instruction/Dockerfile
  testing/examples/run_instruction/test_configs/BUILD
  testing/examples/run_instruction/test_configs/java_python.yaml
Labels: cla: yes, size/L

#757 Allow passwd entry with non-existing home path
  .gitignore
  container/image_test.py
  contrib/passwd.bzl
  testdata/BUILD
Labels: cla: yes, lgtm, needs-ok-to-test, size/M

#755 Return providers instead of struct from rule impl functions
  container/bundle.bzl
  container/flatten.bzl
  container/image.bzl
  container/import.bzl
  container/layer.bzl
  container/layer_tools.bzl
  container/push.bzl
  contrib/push-all.bzl
  lang/image.bzl
Labels: cla: yes, size/L

#769 `legacy_run_behavior` value shouldn't be taken from base.
  README.md
  container/image.bzl
  testdata/BUILD
Labels: cla: yes, size/M
