Repository bazelbuild/rules_docker, pull requests merged in 2019-06, with the labels that each got.

#869 Simple comment change to test CaaS
  container/pull.bzl
Labels: approved, cla: yes, lgtm, size/XS

#867 fast puller argument parser
  container/go/cmd/puller/BUILD
  container/go/cmd/puller/puller.go
Labels: approved, cla: yes, lgtm, size/M

#875 Fix incremental loader cleanup when no run statements are defined
  container/incremental_load.sh.tpl
  container/layer_tools.bzl
Labels: approved, cla: yes, lgtm, size/XS

#870 Add puller function in go
  WORKSPACE
  container/go/cmd/puller/BUILD
  container/go/cmd/puller/puller.go
Labels: approved, cla: yes, lgtm, size/M

#879 Set up GCB job to release go puller binary.
  container/go/cloudbuild.yaml
  container/go/cmd/puller/BUILD
  container/go/cmd/puller/puller.go
Labels: approved, cla: yes, lgtm, size/M

#880 Remove reference to cache which doesn't exist in internal codebase
  container/go/cmd/puller/BUILD
  container/go/cmd/puller/puller.go
Labels: approved, cla: yes, lgtm, size/XS

#882 Read image from OCI image layout
  WORKSPACE
  container/go/pkg/oci/BUILD
  container/go/pkg/oci/reader.go
Labels: approved, cla: yes, lgtm, size/M

#895 Update travis to use xenial test base.
  .travis.yml
  container/pull.bzl
  testdata/BUILD
  testing/e2e.sh
Labels: approved, cla: yes, lgtm, size/M

#876 Expose attributes from lang/image.bzl as struct
  java/image.bzl
  lang/image.bzl
  nodejs/image.bzl
Labels: approved, cla: yes, lgtm, size/M

#894 Implement OCI image puller binary and writer utility
  container/go/cmd/puller/BUILD
  container/go/cmd/puller/puller.go
  container/go/pkg/oci/BUILD
  container/go/pkg/oci/write.go
Labels: approved, cla: yes, lgtm, size/L

#898 Update doc about new examples
  README.md
  testing/examples/README.md
Labels: approved, cla: yes, lgtm, size/XS

#900 Fix input that should be tool.
  container/image.bzl
Labels: approved, cla: yes, lgtm, size/XS

#902 Support using Kaniko to build images.
  WORKSPACE
  contrib/Dockerfile
  contrib/dockerfile_build.bzl
  contrib/kaniko_run_and_extract.sh.tpl
  testdata/dockerfile_build/BUILD
  testdata/dockerfile_build/Data_file.txt
  testdata/dockerfile_build/Dockerfile
  testdata/dockerfile_build/More_data.txt
  testdata/dockerfile_build/file_to_copy.txt
  testing/e2e.sh
  tests/docker/BUILD
  tests/docker/configs/basic_dockerfile.yaml
  tests/docker/configs/dockerfile_image.yaml
Labels: approved, cla: yes, lgtm, size/L

#901 Create new starlark rules for new_container_pull
  WORKSPACE
  container/new_pull.bzl
  repositories/repositories.bzl
  tests/docker/BUILD
Labels: approved, cla: yes, lgtm, size/L

#905 Add better error message when tar is used in container_test docker mode.
  WORKSPACE
  contrib/test.bzl
  tests/docker/BUILD
  tests/docker/configs/dockerfile_image.yaml
Labels: approved, cla: yes, size/M

#899 run dockerfile examples tests
  contrib/dockerfile_build.bzl
  testing/examples/.bazelrc
  testing/examples/WORKSPACE
  testing/examples/basic/cloudbuild.yaml
  testing/examples/extended/cloudbuild.yaml
  testing/examples/java_app/cloudbuild.yaml
  testing/examples/run_instruction_apt_pkgs/Dockerfile
  testing/examples/run_instruction_apt_pkgs/cloudbuild.yaml
  testing/examples/run_instruction_arbitrary/cloudbuild.yaml
Labels: approved, cla: yes, do-not-merge/hold, size/L

#914 Refactor reader tests for better styling
  container/go/pkg/oci/reader_test.go
Labels: approved, cla: yes, lgtm, size/S

#907 Add new Docker tarball feature to Go puller binary
  container/go/cmd/puller/BUILD
  container/go/cmd/puller/puller.go
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/M

#916 fix apt_pkgs example test
  testing/examples/run_instruction_apt_pkgs/cloudbuild.yaml
Labels: approved, cla: yes, lgtm, size/S

#910 Add back reference to cache in new go puller binary
  container/go/cmd/puller/BUILD
  container/go/cmd/puller/puller.go
Labels: approved, cla: yes, lgtm, size/S

#912 Update new_pull.bzl to include cache handling
  container/new_pull.bzl
Labels: approved, cla: yes, lgtm, size/S

#915 Implement new container_push
  container/go/cmd/pusher/BUILD
  container/go/cmd/pusher/pusher.go
  container/new_push.bzl
Labels: approved, cla: yes, lgtm, size/L

#925 Update docs with v0.8.0 release
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#908 Update new_pull.bzl to accommodate new puller binary
  WORKSPACE
  container/new_pull.bzl
  repositories/repositories.bzl
  tests/docker/BUILD
Labels: approved, cla: yes, lgtm, size/M

#924 Prefer docker_run_flags from ctx when present
  container/image.bzl
  testdata/BUILD
  testing/e2e.sh
Labels: approved, cla: yes, lgtm, size/M

#926 Clarify end user details for war_image macro
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#928 Implement new loader.go binary
  container/go/cmd/loader/BUILD
  container/go/cmd/loader/loader.go
Labels: approved, cla: yes, lgtm, size/L

#930 Add loader to GCB release job.
  container/go/cloudbuild.yaml
Labels: approved, cla: yes, lgtm, size/S

#932 Fix Bazel race condition in go binary release job.
  container/go/cloudbuild.yaml
Labels: approved, cla: yes, lgtm, size/S

#931 Add tests for new container_push
  container/go/cmd/pusher/pusher.go
  container/go/pkg/oci/BUILD
  container/new_push.bzl
  testdata/BUILD
  testdata/go_pusher_test.tar
  testing/custom_toolchain_auth/WORKSPACE
  testing/default_toolchain/WORKSPACE
  testing/e2e.sh
  tests/docker/BUILD
Labels: approved, cla: yes, lgtm, size/L

#929 Add new Starlark container load rule new_load.bzl
  WORKSPACE
  container/new_load.bzl
  repositories/repositories.bzl
  tests/docker/BUILD
Labels: approved, cla: yes, lgtm, size/L

#937 Update release notes for 0.8.1
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#934 Refactor write.go test with small image
  container/go/pkg/oci/testdata/test_write1/small_linux.tar
  container/go/pkg/oci/write_test.go
Labels: approved, cla: yes, lgtm, size/L

#938 migrating content from e2e.sh to separate, more granular, GCB builds
  testing/e2e.sh
  testing/e2e/cc_image.sh
  testing/e2e/go_image.sh
  testing/e2e/test_cc_image.yaml
  testing/e2e/test_go_image.yaml
  testing/e2e/util.sh
Labels: approved, cla: yes, lgtm, size/L
