Repository bazelbuild/rules_docker, pull requests merged in 2019-10, with the labels that each got.

#1173 register toolchain only for container exec and use it in py*_image
  .bazelci/presubmit.yml
  README.md
  WORKSPACE
  contrib/repro_test.bzl
  platforms/BUILD
  python/image.bzl
  python3/image.bzl
  tests/contrib/BUILD
  toolchains/BUILD
Labels: approved, cla: yes, lgtm, size/L

#1181 Update README for release v0.11.0
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1183 fix bug in toolchain_layers.bzl
  docker/toolchain_container/toolchain_container.bzl
  tests/docker/toolchain_container/BUILD
Labels: approved, cla: yes, lgtm, size/M

#1182 fix rules_docker with bazel head
  WORKSPACE
  python/image.bzl
  python3/image.bzl
  toolchains/py_toolchains.bzl
Labels: approved, cla: yes, lgtm, size/L

#1186 Deprecate python puller, loader & pusher.
  container/legacy_load.bzl
  container/legacy_pull.bzl
  container/legacy_push.bzl
  repositories/repositories.bzl
Labels: approved, cla: yes, lgtm, size/XL

#1188 Update README.md
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1190 fixing rules_docker with bazel head
  platforms/BUILD
Labels: approved, cla: yes, lgtm, size/XS

#1191 Final fixes for mac using toolchains properly in py_binary target with bazel head
  toolchains/py_toolchains.bzl
Labels: approved, cla: yes, lgtm, size/S

#1195 Update README & bazelrc
  .bazelrc
  README.md
  testing/download_pkgs_at_root/.bazelrc
  testing/examples/.bazelrc
Labels: approved, cla: yes, lgtm, size/M

#1197 update go containerregistry for #1193
  repositories/go_repositories.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1200 Support env vars that contain '='
  container/go/pkg/compat/config.go
  tests/container/BUILD
  tests/container/configs/set_env_equals.yaml
Labels: approved, cla: yes, lgtm, size/S

#1201 Fix writing uncompressed images & add test
  container/go/pkg/compat/BUILD
  container/go/pkg/compat/write.go
  container/go/pkg/compat/write_test.go
Labels: approved, cla: yes, lgtm, size/L

#1202 update container dependencies
  cc/cc.bzl
  go/go.bzl
  go/static.bzl
  java/java.bzl
  java/jetty.bzl
  nodejs/nodejs.bzl
  python/python.bzl
  python3/python3.bzl
Labels: approved, cla: yes, lgtm, size/M

#1206 making changes to simplify py toolchains
  .bazelci/presubmit.yml
  WORKSPACE
  python/image.bzl
  python3/image.bzl
  toolchains/py_toolchains.bzl
Labels: approved, cla: yes, size/L

#1218 Fix reference to //platforms to include @io_bazel_rules_docker
  python/image.bzl
  python3/image.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1205 testing changes to platforms to enable #1203 to work
  .bazelci/presubmit.yml
  .bazelrc
  docker/security/BUILD
  docker/security/cmd/json_to_yaml/BUILD
  docker/security/cmd/json_to_yaml/json_to_yaml.go
  docker/security/security_check.bzl
  docker/security/security_check.py
  docker/util/BUILD
  docker/util/config_stripper.py
  repositories/go_repositories.bzl
Labels: approved, cla: yes, size/L

#1225 Update go-containerregistry to fix panic in image tarball writer
  repositories/go_repositories.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1226 Fixes for python use in download_pkgs
  WORKSPACE
  docker/package_managers/download_pkgs.bzl
  docker/package_managers/run_download.sh.tpl
  python/image.bzl
  python3/image.bzl
Labels: approved, cla: yes, lgtm, size/M

#1229 Make pusher emit error if client config is not a valid directory
  README.md
  container/go/cmd/pusher/pusher.go
  testing/e2e/pusher.sh
  testing/e2e/test_pusher.yaml
Labels: approved, cla: yes, lgtm, size/M

#1230 update go containerregistry
  repositories/go_repositories.bzl
Labels: approved, cla: yes, size/XS

#1236 Add new adopter
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1238 update bazel-toolchains and fix reference to exec_propertiers:
  WORKSPACE
  testing/download_pkgs_at_root/WORKSPACE
Labels: approved, cla: yes, lgtm, size/S

#1237 Added Documentation for container_layer for empty_dirs
  README.md
Labels: approved, cla: yes, lgtm, size/S

#1244 Fix pip in py3_image
  python3/image.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1249 Update README for release v0.12.1
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1251 Fix rules_go mirror URL
  repositories/repositories.bzl
Labels: approved, cla: yes, lgtm, size/XS
