Repository bazelbuild/rules_docker, pull requests merged in 2019-08, with the labels that each got.

#1023 Modify container_push and container_image to use new digester
  container/go/cmd/digester/digester.go
  container/go/cmd/pusher/pusher.go
  container/go/pkg/compat/BUILD
  container/go/pkg/compat/generateManifest.go
  container/go/pkg/compat/reader.go
  container/go/pkg/utils/utils.go
  container/image.bzl
  container/new_push.bzl
  container/push.bzl
  container/utils.bzl
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/L

#1044 Add utils.bzl to bzl_library
  container/BUILD
Labels: approved, cla: yes, lgtm, size/XS

#1045 upgrade gazelle and fix issue with one of the samples
  repositories/repositories.bzl
  testing/examples/BUILD
Labels: approved, cla: yes, lgtm, size/S

#1047 Use the default shell for docker commands
  docker/package_managers/download_pkgs.bzl
  docker/package_managers/install_pkgs.bzl
  docker/util/run.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1048 Remove java pkg non-determinism test
  .bazelci/presubmit.yml
  tests/contrib/BUILD
  tests/contrib/repro_imgs.yaml
Labels: approved, cla: yes, lgtm, size/S

#1050 Deprecate indeterminism detector
  contrib/BUILD
  contrib/idd.bzl
  contrib/idd.py
  tests/contrib/BUILD
Labels: approved, cla: yes, lgtm, size/XL

#1046 Refactor legacy image formats to not generate symlinks
  container/BUILD
  container/go/cmd/digester/digester.go
  container/go/cmd/pusher/pusher.go
  container/go/pkg/compat/BUILD
  container/go/pkg/compat/generateManifest.go
  container/go/pkg/compat/image.go
  container/go/pkg/compat/path.go
  container/go/pkg/compat/reader.go
  container/go/pkg/utils/utils.go
  container/image.bzl
  container/new_push.bzl
  container/push.bzl
  container/utils.bzl
Labels: approved, cla: yes, size/L

#1056 Escape backslashes in Starlark code
  container/image.bzl
  contrib/repro_test.bzl
  docker/package_managers/apt_key.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1057 Fix semantic test failure in CI
  tests/contrib/automatic_container_release/BUILD
  tests/contrib/automatic_container_release/deps_spec_no_fus_deps.yaml
Labels: approved, cla: yes, lgtm, size/M

#1058 Revert digester deps for container_push and container_image
  container/image.bzl
  container/push.bzl
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/M

#1060 Updated new puller binary to generate digest file
  container/go/cmd/digester/BUILD
  container/go/cmd/digester/digester.go
  container/go/cmd/puller/puller.go
  container/go/pkg/compat/ociToLegacy.go
Labels: approved, cla: yes, lgtm, size/M

#1061 Add image digest in new puller starlark rule
  container/go/pkg/compat/testdata/test_index1/0.sha256
  container/go/pkg/compat/testdata/test_index1/0.tar.gz
  container/go/pkg/compat/testdata/test_index1/1.sha256
  container/go/pkg/compat/testdata/test_index1/1.tar.gz
  container/go/pkg/compat/testdata/test_index1/2.sha256
  container/go/pkg/compat/testdata/test_index1/2.tar.gz
  container/go/pkg/compat/testdata/test_index1/BUILD
  container/go/pkg/compat/testdata/test_index1/config.json
  container/go/pkg/compat/testdata/test_index1/digest
  container/go/pkg/compat/testdata/test_index1/manifest.json
  container/new_pull.bzl
  container/pull.bzl
  repositories/repositories.bzl
Labels: approved, cla: yes, lgtm, size/M

#1042 Issue 1022 update readme with details on known issue
  README.md
Labels: approved, cla: no, do-not-merge/hold, lgtm, size/S

#1062 Implement createImageConfig for use in container_image targets
  container/go/cmd/create_image_config/BUILD
  container/go/cmd/create_image_config/createImageConfig.go
  container/go/pkg/compat/BUILD
  container/go/pkg/compat/overrideConfig.go
Labels: approved, cla: yes, lgtm, size/XL

#1032 Support stamping in new pusher
  container/go/cmd/pusher/pusher.go
  container/new_push.bzl
  testing/e2e.sh
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/M

#1063 Update image.bzl to optionally utilize new createImageConfig Go binary
  container/image.bzl
Labels: approved, cla: yes, lgtm, size/L

#1066 Add documentation for new_container_pull
  README.md
  container/new_pull.bzl
Labels: approved, cla: yes, lgtm, size/L

#1069 update base images
  cc/cc.bzl
  go/go.bzl
  go/static.bzl
  java/java.bzl
  java/jetty.bzl
  nodejs/nodejs.bzl
  python/python.bzl
  python3/python3.bzl
Labels: approved, cla: yes, lgtm, size/M

#1065 Add digest test for new puller
  .bazelci/presubmit.yml
  container/go/cmd/digester/digester.go
  container/go/cmd/pusher/pusher.go
  container/go/pkg/compat/generateManifest.go
  container/go/pkg/oci/reader.go
  testing/e2e.sh
  tests/container/BUILD
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/M

#1067 Add documentation for new_container_push
  README.md
Labels: approved, cla: yes, lgtm, size/L

#1070 Fix typo in links
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1071 change exec -> executable as var name
  container/image.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1073 clarify docs for use of client_config
  README.md
  toolchains/docker/toolchain.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1074 Clarify when not to use custom pull rule
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1082 README.md: add the K8s Container Image Promoter to adopters
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1081 Update OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1080 Update CODEOWNERS
  CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1084 Add xz_path to default toolchain
  toolchains/docker/BUILD
Labels: approved, cla: yes, lgtm, size/XS

#1086 Revert "Add xz_path to default toolchain"
  toolchains/docker/BUILD
Labels: approved, cla: yes, lgtm, size/XS

#1091 Update readme with new download instructions
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1088 Add (again) xz_path to default toolchain"
  toolchains/docker/BUILD
Labels: approved, cla: yes, size/XS

#1092 Revert "Add (again) xz_path to default toolchain""
  toolchains/docker/BUILD
Labels: approved, cla: yes, lgtm, size/XS

#1099 Update openjdk gpg file sha256
  WORKSPACE
Labels: approved, cla: yes, lgtm, size/XS

#1100 Add xz to default toolchain again
  toolchains/docker/BUILD
Labels: approved, cla: yes, lgtm, size/XS

#1101 Update rules_groovy pin
  WORKSPACE
  tests/container/groovy/configs/groovy_image.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1115 Enable specifying a tag for the checker image in configs_test
  contrib/automatic_container_release/configs_test.bzl
Labels: approved, cla: yes, size/XS

#1112 Add a flag to control pushing new tags on unchanged images
  container/go/cmd/pusher/BUILD
  container/go/cmd/pusher/pusher.go
  container/new_push.bzl
  testing/e2e.sh
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/L

#1117 Add Button to list of users
  README.md
Labels: approved, cla: yes, lgtm, size/XS
