Repository bazelbuild/rules_docker, pull requests merged in 2019-02, with the labels that each got.

#681 License should be at top.
  BUILD
  container/BUILD
  docker/BUILD
  skylib/BUILD
  testdata/BUILD
  testdata/pause_piecemeal/BUILD
  testdata/pause_piecemeal_gz/BUILD
  testdata/test/BUILD
  tests/docker/BUILD
  tests/docker/cc/BUILD
  tests/docker/go/BUILD
  tests/docker/groovy/BUILD
  tests/docker/java/BUILD
  tests/docker/nodejs/BUILD
  tests/docker/python/BUILD
  tests/docker/python3/BUILD
  tests/docker/rust/BUILD
  tests/docker/scala/BUILD
  toolchains/docker/BUILD
Labels: cla: yes, lgtm, size/L

#684 fixed targeting
  README.md
Labels: cla: yes, lgtm, needs-ok-to-test, size/XS

#686 Toolchain auth docs
  README.md
Labels: cla: yes, lgtm, size/M

#687 Add new adopters section for rules_docker
  README.md
Labels: cla: yes, lgtm, size/XS

#688 add etsy to adopters
  README.md
Labels: cla: yes, lgtm, needs-ok-to-test, size/XS

#692 Add more adopters
  README.md
Labels: cla: yes, lgtm, size/XS

#695 Set default_mtime=0 on TarFileWriter so that elements default to the epoch
  container/BUILD
  container/build_tar.py
  container/image_test.py
  repositories/repositories.bzl
Labels: cla: yes, size/S

#685 Update to container-structure-test 1.8.0
  repositories/repositories.bzl
Labels: cla: yes, lgtm, needs-ok-to-test, size/XS

#696 Use internally downloaded @six and disable legacy_create_init
  container/BUILD
  contrib/BUILD
  tools/BUILD
Labels: cla: yes, lgtm, needs-ok-to-test, size/S
