Repository bazelbuild/rules_docker, pull requests merged in 2019-05, with the labels that each got.

#821 Mark Python binaries with explicit python_version.
  container/BUILD
  contrib/BUILD
  testdata/BUILD
  tests/container/BUILD
  tools/BUILD
Labels: approved, cla: yes, size/S

#826 test use of incompatible_use_python_toolchains flag with Bazel 0.25.0
  .bazelci/presubmit.yml
  .bazelignore
  .bazelrc
  README.md
  WORKSPACE
  python/BUILD
  python/image.bzl
  python3/image.bzl
  toolchains/python/BUILD
Labels: approved, cla: yes, lgtm, size/L

#828 Add feature to pass --build-arg to dockerfile_image rule.
  .bazelci/presubmit.yml
  WORKSPACE
  contrib/Dockerfile
  contrib/dockerfile_build.bzl
  tests/docker/configs/basic_dockerfile.yaml
Labels: approved, cla: yes, lgtm, size/M

#829 doc(readme): add "Tink" as user of `rules_docker`
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#830 Add initial skeleton for go implementation of image_config.py
  BUILD
  WORKSPACE
  container/go/cmd/extract_config/BUILD
  container/go/cmd/extract_config/main.go
Labels: approved, cla: yes, size/M

#840 Fix for Bazel upcoming change incompatible_string_join_requires_strings
  contrib/test.bzl
Labels: approved, cla: yes, lgtm, size/XS

#841 move gazelle target to repositories.bzl
  WORKSPACE
  repositories/repositories.bzl
Labels: approved, cla: yes, lgtm, size/S

#851 Update rules_go to 0.18.5
  WORKSPACE
Labels: approved, cla: yes, lgtm, size/XS

#856 use bazel-toolchains tag releases and standard bazel container
  WORKSPACE
Labels: approved, cla: yes, lgtm, size/S

#864 container_test verbose should drive verbosity
  contrib/test.bzl
Labels: approved, cla: yes, lgtm, size/XS
