Repository bazelbuild/rules_docker, pull requests merged in 2019-04, with the labels that each got.

#773 Add more doc about `legacy_run_behavior`.
  README.md
  container/image.bzl
Labels: cla: yes, lgtm, size/XS

#777 enable tests that require XZ on rbe
  .bazelci/presubmit.yml
  WORKSPACE
Labels: cla: yes, lgtm, size/M

#778 remove TODO for bazel_source pin
  .bazelci/presubmit.yml
  container/BUILD
  container/build_tar.py
  repositories/repositories.bzl
Labels: cla: yes, lgtm, size/S

#783 updating containerregistry pin
  repositories/repositories.bzl
Labels: cla: yes, lgtm, size/XS

#785 add owners file
  OWNERS
Labels: cla: yes, lgtm, size/S

#793 Add cleanup before docker run in incremental loader
  container/incremental_load.sh.tpl
Labels: cla: yes, lgtm, needs-ok-to-test, size/XS

#796 Add Dockerfile example that handles an arbitrary RUN instruction
  testing/examples/WORKSPACE
  testing/examples/run_instruction_apt_pkgs/BUILD
  testing/examples/run_instruction_apt_pkgs/Dockerfile
  testing/examples/run_instruction_apt_pkgs/test_configs/BUILD
  testing/examples/run_instruction_apt_pkgs/test_configs/java_python.yaml
  testing/examples/run_instruction_arbitrary/BUILD
  testing/examples/run_instruction_arbitrary/Dockerfile
  testing/examples/run_instruction_arbitrary/test_configs/BUILD
  testing/examples/run_instruction_arbitrary/test_configs/bazel_gcloud.yaml
Labels: approved, cla: yes, lgtm, size/L

#800 use ubuntu18.04 in buildkite CI
  .bazelci/presubmit.yml
Labels: approved, cla: yes, lgtm, size/S

#802 Don't test on Ubuntu 14.04
  .bazelci/presubmit.yml
Labels: approved, cla: yes, size/S

#810 Update renovate to run weekly
  renovate.json
Labels: approved, cla: yes, lgtm, size/XS

#812 Add company that uses rules_docker in production.
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#819 modify how stamp-info-file is calculated
  container/push.bzl
Labels: approved, cla: yes, lgtm, size/XS
