Repository bazelbuild/rules_docker, pull requests merged in 2020-01, with the labels that each got.

#1352 Sync with internal change
  README.md
  WORKSPACE
  contrib/repro_test.bzl
  docker/util/extract.sh.tpl
  tests/contrib/BUILD
Labels: approved, cla: yes, lgtm, size/S

#1353 Add robot_email attr to container push bzl rules
  container/push.bzl
  contrib/push-all.bzl
Labels: approved, cla: yes, size/S

#1355 Revert "Add robot_email attr to container push bzl rules"
  container/push.bzl
  contrib/push-all.bzl
Labels: approved, cla: yes, lgtm, size/S

#1357 update_deps in Go
  container/go/cmd/update_deps/BUILD
  container/go/cmd/update_deps/update_deps.go
  repositories/go_repositories.bzl
  tools/update_deps.py
  update_deps.sh
Labels: approved, cla: yes, lgtm, size/L

#1358 Add Canva to adopters list
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1318 Change to using python 3 in host configuration
  container/BUILD
  contrib/BUILD
  testdata/BUILD
  testing/e2e.sh
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/S

#1360 Revert "Change to using python 3 in host configuration"
  container/BUILD
  contrib/BUILD
  testdata/BUILD
  testing/e2e.sh
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/S

#1302 Use 'portable' mtime as default for tars, like rules_pkg does
  container/build_tar.py
  container/layer.bzl
Labels: approved, cla: yes, do-not-merge/hold, size/S

#1359 Add http(s)_proxy env var support to puller
  container/go/cmd/puller/puller.go
Labels: approved, cla: yes, size/XS

#1365 update puller and loader binaries to pick up #1359
  repositories/repositories.bzl
Labels: approved, cla: yes, lgtm, size/S

#1366 update rules_groovy call to repositories.bzl
  WORKSPACE
Labels: approved, cla: yes, lgtm, size/S

#1367 Path join issues in contrib/dockerfile_build.bzl
  container/puller.par
  contrib/dockerfile_build.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1369 Get build args from eviron in dockerfile build
  WORKSPACE
  contrib/dockerfile_build.bzl
  testdata/dockerfile_build/Dockerfile
  tests/contrib/configs/dockerfile_image.yaml
Labels: approved, cla: yes, lgtm, size/S

#1372 remove par file that was checked in by mistake
  container/puller.par
Labels: approved, cla: yes, lgtm, size/XS

#1375 update rules scala to pick up maven to https change
  WORKSPACE
  java/image.bzl
Labels: approved, cla: yes, lgtm, size/S

#1376 update README for v0.14.0
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1377 Implement UncompressedSize to take advantage of memory opt
  container/go/pkg/compat/image.go
  repositories/go_repositories.bzl
Labels: approved, cla: yes, lgtm, size/S

#1379 fix repro tests
  contrib/repro_test.bzl
Labels: approved, cla: yes, lgtm, size/S

#1380 Update README.md for v0.14.1
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1371 Not all rules have deps, don't assume they exist
  lang/image.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1346 add layer for npm packages
  README.md
  WORKSPACE
  container/BUILD
  container/image_test.py
  nodejs/image.bzl
  testdata/BUILD
  testdata/nodejs_image.js
  testdata/nodejs_image_lib.ts
  testdata/package.json
  testdata/tsconfig.json
  testdata/yarn.lock
  tests/container/nodejs/BUILD
Labels: approved, cla: yes, lgtm, size/L

#1390 Update dependency @types/node to v12.12.25
  container/image_test.py
  testdata/package.json
  testdata/yarn.lock
Labels: approved, cla: yes, lgtm, size/L

#1391 Declare PATH environment variable as a dependency.
  toolchains/docker/toolchain.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1394 update alpine sha
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/XS
