Repository bazelbuild/rules_docker, pull requests merged in 2020-04, with the labels that each got.

#1481 Sync with internal change
  testdata/BUILD
Labels: approved, cla: yes, lgtm, size/XS

#1480 java_files() already returns a depset, don't wrap the return value in
  java/image.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1477 Inject docker headers for container pushes
  container/go/cmd/pusher/pusher.go
Labels: approved, cla: yes, lgtm, size/M

#1483 Use rules_pkg repository instead of deprecated pkg files
  README.md
  container/BUILD
  container/build_tar.py
  repositories/repositories.bzl
  testdata/BUILD
  tests/docker/toolchain_container/BUILD
Labels: approved, cla: yes, lgtm, size/S

#1484 Update one remaining reference to deprecated rules pkg
  container/BUILD
  testdata/extras_gen.py
Labels: approved, cla: yes, lgtm, size/XS

#1485 Enable mtime preservation in tar file building process
  container/build_tar.py
  container/image_test.py
  repositories/repositories.bzl
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/M
