Repository bazelbuild/rules_docker, pull requests merged in 2020-09, with the labels that each got.

#1610 Add Linux ARM64 go pusher and loader binaries to cloudbuild
  container/go/cloudbuild.yaml
Labels: approved, cla: yes, lgtm, size/M

#1613 For gzip operations, use a new Go helper by default instead of which(gzip)
  README.md
  container/BUILD
  container/go/cmd/zipper/BUILD
  container/go/cmd/zipper/zipper.go
  container/import.bzl
  container/layer.bzl
  skylib/zip.bzl
  testing/default_toolchain/WORKSPACE
  tests/container/BUILD
  toolchains/docker/toolchain.bzl
Labels: approved, cla: yes, lgtm, size/L

#1609 Fix the root directory when building for Linux on Windows.
  container/layer.bzl
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/XS

#1618 Add repository_file attribute to the container_pull rule
  container/push.bzl
Labels: approved, cla: yes, lgtm, size/S

#1619 Support airgapped environment
  repositories/go_repositories.bzl
Labels: approved, cla: yes, lgtm, size/S

#1589 Fix the typos in root README
  README.md
Labels: approved, cla: yes, do-not-merge/hold, size/XS

#1626 Port image_test & testdata targets to python3
  WORKSPACE
  container/BUILD
  container/image_test.py
  repositories/repositories.bzl
  testdata/BUILD
Labels: approved, cla: yes, lgtm, size/M

#1627 Port another test image target to py3 & fix src compatibility of another
  testdata/BUILD
Labels: approved, cla: yes, lgtm, size/XS

#1621 Avoid using os.path.normpath on Windows with files destined for Linux.
  container/build_tar.py
  container/layer.bzl
Labels: approved, cla: yes, lgtm, size/S

#1586 Add container_run_and_commit_layer rule
  .bazelci/presubmit.yml
  contrib/BUILD
  contrib/extract_last_layer.py
  docker/util/BUILD
  docker/util/README.md
  docker/util/commit_layer.sh.tpl
  docker/util/run.bzl
  tests/docker/util/BUILD
  tests/docker/util/container_commit_layer.yaml
Labels: approved, cla: yes, lgtm, size/L

#1635 Run update_deps.sh.
  go/go.bzl
Labels: approved, cla: yes, lgtm, size/XS
