Repository bazelbuild/rules_docker, pull requests merged in 2020-02, with the labels that each got.

#1412 Update rules_scala
  WORKSPACE
  tests/container/scala/configs/scala_image.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1396 Create kotlin_jvm_image rule
  WORKSPACE
  kotlin/BUILD
  kotlin/image.bzl
  testdata/BUILD
  testdata/Binary.kt
  testdata/Library.kt
  testing/e2e/kt_jvm_image.sh
  testing/e2e/test_kt_jvm_image.yaml
  tests/container/kotlin/BUILD
  tests/container/kotlin/configs/BUILD
  tests/container/kotlin/configs/kt_jvm_image.yaml
Labels: approved, cla: yes, lgtm, size/L

#1427 Expose architecture in container_image
  .bazelci/presubmit.yml
  README.md
  container/go/cmd/create_image_config/create_image_config.go
  container/go/pkg/compat/config.go
  container/image.bzl
  tests/container/BUILD
  tests/container/architecture_test.sh
Labels: approved, cla: yes, lgtm, size/M

#1428 Allow setting compression method and options.
  README.md
  container/BUILD
  container/image.bzl
  container/image_test.py
  container/layer.bzl
  skylib/zip.bzl
  testdata/BUILD
Labels: approved, cla: yes, lgtm, size/L

#1430 Plumb os.version through container image config files.
  README.md
  container/go/cmd/create_image_config/create_image_config.go
  container/go/pkg/compat/config.go
  container/image.bzl
  repositories/go_repositories.bzl
  testing/e2e.sh
Labels: approved, cla: yes, size/M

#1437 pass tag/visiblity to nodejs_image dep layers
  nodejs/image.bzl
Labels: cla: yes, lgtm, size/XS
