Repository bazelbuild/rules_docker, pull requests merged in 2020-06, with the labels that each got.

#1522 Switch arbitrary run instruction to python3
  testing/examples/run_instruction_arbitrary/BUILD
  testing/examples/run_instruction_arbitrary/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#1517 update puller and loader binaries to pich up #1509
  repositories/repositories.bzl
Labels: approved, cla: yes, size/S

#1526 Populate list of instrumented files for coverage in container_image_
  container/image.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1527 Update debs attr doc & other minor fixes
  README.md
Labels: approved, cla: yes, lgtm, size/M

#1528 Update go dependency & Bazel test image
  WORKSPACE
  contrib/repro_test.bzl
  repositories/repositories.bzl
  tests/contrib/BUILD
Labels: approved, cla: yes, lgtm, size/S

#1534 Migrate to use absl from gflags
  container/BUILD
  container/build_tar.py
  repositories/repositories.bzl
Labels: approved, cla: yes, lgtm, size/M

#1535 Revert to using gflags but use it from a pips package instead of Bazel Tools
  container/BUILD
  container/build_tar.py
  repositories/requirements-pip.txt
  testing/custom_toolchain_auth/WORKSPACE
  testing/custom_toolchain_flags/WORKSPACE
  testing/default_toolchain/WORKSPACE
  testing/download_pkgs_at_root/WORKSPACE
  testing/e2e.sh
  testing/e2e/top_level.sh
  testing/examples/WORKSPACE
  testing/java_image/WORKSPACE
  testing/new_pusher_tests/WORKSPACE
Labels: approved, cla: yes, lgtm, size/L

#1536 Remove unused dep
  repositories/repositories.bzl
Labels: approved, cla: yes, lgtm, size/M

#1537 Dont write incremental tarball to disk
  container/incremental_load.sh.tpl
Labels: approved, cla: yes, lgtm, size/XS

#1531 Update node version
  container/image_test.py
  testdata/package.json
  testdata/yarn.lock
Labels: approved, cla: yes, lgtm, size/S
