Repository bazelbuild/rules_docker, pull requests merged in 2020-11, with the labels that each got.

#1657 Update python rules to remove deprecation messages
  README.md
  WORKSPACE
  container/image_test.py
  repositories/BUILD
  repositories/pip_repositories.bzl
  repositories/py_repositories.bzl
Labels: approved, cla: yes, lgtm, size/XXL

#1668 Remove release pin from README
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1665 Update owners
  CODEOWNERS
  OWNERS
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/XS

#1658 Add option to push images sequentially in push-all
  contrib/push-all.bzl
  contrib/push-all.sh.tpl
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/S

#1661 Add s390x support to load puller and loader binary
  container/load.bzl
  container/pull.bzl
  repositories/repositories.bzl
Labels: approved, cla: yes, lgtm, size/M

#1666 Fix update_deps to grab correct platform digest, rerun
  cc/cc.bzl
  container/go/cmd/update_deps/BUILD
  container/go/cmd/update_deps/update_deps.go
  go/go.bzl
  java/java.bzl
  java/jetty.bzl
  python/python.bzl
  python3/python3.bzl
  repositories/go_repositories.bzl
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/M

#1671 Add arm64 support to load puller and loader binaries
  container/load.bzl
  container/pull.bzl
  repositories/repositories.bzl
Labels: approved, cla: yes, size/M

#1675 Fix invalid escape sequence
  container/push.bzl
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/XS

#1676 Fix more invalid escape sequences
  tests/contrib/BUILD
  tests/docker/util/BUILD
Labels: approved, cla: yes, lgtm, size/XS

#1677 Relax error string matching
  testing/e2e.sh
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/XS

#1674 Fix select with condition on darwin.
  contrib/BUILD
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/XS
