Repository bazelbuild/rules_docker, pull requests merged in 2020-12, with the labels that each got.

#1672 Fix Stamp param propagation from base image
  container/BUILD
  container/image.bzl
  container/image_test.py
  container/providers.bzl
  testdata/BUILD
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/M

#1673 Improve portability of download_pkgs genrule bash
  docker/package_managers/download_pkgs.bzl
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/XS

#1696 Add experimental_tarball_format to container_image
  container/BUILD
  container/bundle.bzl
  container/go/cmd/join_layers/join_layers.go
  container/image.bzl
  container/import.bzl
  container/layer_tools.bzl
  testdata/BUILD
Labels: approved, cla: yes, lgtm, size/M

#1685 Introduce output_group for pusher executable
  container/push.bzl
Labels: approved, cla: yes, lgtm, size/XS
