Repository bazelbuild/rules_docker, pull requests merged in 2020-05, with the labels that each got.

#1488 Revert "Enable mtime preservation in tar file building process (#1485)"
  container/build_tar.py
  container/image_test.py
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/S

#1490 Update node pins
  WORKSPACE
  container/image_test.py
  testdata/package.json
  testdata/yarn.lock
Labels: approved, cla: yes, lgtm, size/M

#1489 Allow users to opt into mtime preservation
  container/build_tar.py
  container/layer.bzl
Labels: approved, cla: yes, lgtm, size/S

#1491 Correctly read users' enable_mtime_preservation config
  container/BUILD
  container/build_tar.py
  container/image_test.py
  testdata/BUILD
Labels: approved, cla: yes, lgtm, size/S

#1505 Convert a few targets/tests to python 3
  testdata/BUILD
  testdata/test/BUILD
  tests/container/BUILD
  tests/container/python/BUILD
Labels: approved, cla: yes, lgtm, size/S

#1513 Fix sha256 for bazel-release.pub.gpg
  WORKSPACE
Labels: approved, cla: yes, lgtm, size/XS

#1495 Fix bug in image puller execution timeout
  container/pull.bzl
  testing/e2e/puller.sh
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/S

#1509 Updated go-containerregistry version
  repositories/go_repositories.bzl
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/XS

#1507 Exposing external base image properties (as provider fields)
  container/import.bzl
  container/providers.bzl
  container/pull.bzl
  tests/container/BUILD
  tests/container/pull_info_validation_test.bzl
Labels: approved, cla: yes, lgtm, size/L

#1516 Update README for 0.14.2. Fixes #1515
  README.md
Labels: approved, cla: yes, lgtm, size/XS
