Repository bazelbuild/rules_docker, pull requests merged in 2020-03, with the labels that each got.

#1450 Fix CI failures due to Clang 10 -> 11 upgrade
  WORKSPACE
  tests/container/cloudbuild.yaml
Labels: approved, cla: yes, lgtm, size/S

#1449 Fixed passing data to app_layer in nodejs_image
  nodejs/image.bzl
Labels: approved, cla: yes, do-not-merge/hold, size/XS

#1453 docs(container image): add info for cmd and entrypoint regarding "" & []
  README.md
Labels: approved, cla: yes, lgtm, size/S

#1461 Sync with internal change
  contrib/BUILD
Labels: approved, cla: yes, lgtm, size/XS

#1462 Sync with internal change
  CODEOWNERS
  contrib/BUILD
Labels: approved, cla: yes, lgtm, size/XS

#1467 Fix puller timeout argument
  container/pull.bzl
Labels: approved, cla: yes, lgtm, size/XS
