Repository bazelbuild/rules_docker, pull requests merged in 2020-10, with the labels that each got.

#1640 Reduce build verbosity of container_run_and_commit
  docker/util/commit.sh.tpl
Labels: approved, cla: yes, lgtm, size/XS

#1639 Plumb constraints thru container_test
  contrib/BUILD
  contrib/test.bzl
  repositories/repositories.bzl
Labels: approved, cla: yes, lgtm, size/S

#1637 Support container_push on Windows.
  container/BUILD
  container/push-tag.bat.tpl
  container/push.bzl
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/M

#1646 Update owners
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1576 Renamed pip_deps to container_pip_deps
  README.md
  WORKSPACE
  container/image_test.py
  repositories/pip_repositories.bzl
  repositories/py_repositories.bzl
  testdata/BUILD
  testdata/test/BUILD
Labels: approved, cla: yes, lgtm, size/L

#1650 Update for compatibility with rules_python 0.1
  repositories/py_repositories.bzl
  repositories/repositories.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1660 Use bash from the environment instead of absolute path
  contrib/cmp_images.sh.tpl
  docker/package_managers/download_pkgs.bzl
  docker/package_managers/installer.sh.tpl
  docker/package_managers/run_download.sh.tpl
  docker/package_managers/run_install.sh.tpl
  docker/util/commit.sh.tpl
  docker/util/commit_layer.sh.tpl
  docker/util/extract.sh.tpl
  docker/util/image_util.sh.tpl
  testdata/cc_image_wrapper.sh
  testing/download_pkgs_at_root/download_pkgs_at_root_run_test.sh
  tests/container/architecture_test.sh
  tests/container/pull_info_validation_test.bzl
  tests/contrib/compare_ids_fail_test.sh.tpl
  tests/contrib/mv_project_root.sh
  tests/contrib/rename_image_test.sh
  tests/docker/package_managers/download_pkgs_run_test.sh
  tests/docker/package_managers/download_pkgs_with_additional_repos_run_test.sh
  tests/docker/package_managers/test_complex_packages.sh
Labels: approved, cla: yes, lgtm, size/M
