Repository bazelbuild/rules_docker, pull requests merged in 2020-07, with the labels that each got.

#1549 Update README for release v0.14.4
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1552 Update pip setup in README
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#1556 Add archive manipulation logic from rules_pkg
  container/BUILD
  container/archive.py
  container/build_tar.py
  testdata/BUILD
  testdata/extras_gen.py
Labels: approved, cla: yes, lgtm, size/L

#1569 [Update] go-containerregistry to fix `container_bundle` rule
  repositories/go_repositories.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1571 Change image rule to copy config instead of symlink
  container/image.bzl
  docker/package_managers/apt_key.bzl
  docker/toolchain_container/debian_pkg_tar.bzl
Labels: approved, cla: yes, lgtm, size/S
