Repository bazelbuild/rules_docker, pull requests merged in 2020-08, with the labels that each got.

#1578 Sync with internal change
  cc/BUILD
  contrib/BUILD
  d/BUILD
  go/BUILD
  groovy/BUILD
  java/BUILD
  oci/BUILD
  python/BUILD
  python3/BUILD
  repositories/BUILD
  rust/BUILD
  scala/BUILD
  testdata/BUILD
  testdata/pause_piecemeal/BUILD
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/L

#1580 Make toolchain_type public
  toolchains/docker/BUILD
Labels: approved, cla: yes, lgtm, size/XS

#1582 Replace dependency on gflags with argparse
  container/BUILD
  container/build_tar.py
  repositories/requirements-pip.txt
  testing/custom_toolchain_auth/WORKSPACE
  testing/custom_toolchain_flags/WORKSPACE
  testing/default_toolchain/WORKSPACE
  testing/download_pkgs_at_root/WORKSPACE
  testing/e2e/top_level.sh
  testing/examples/WORKSPACE
  testing/java_image/WORKSPACE
  testing/new_pusher_tests/WORKSPACE
Labels: approved, cla: yes, lgtm, size/L

#1595 Update dependencies
  WORKSPACE
  container/image_test.py
  testdata/BUILD
  testdata/package.json
  testdata/yarn.lock
Labels: approved, cla: yes, lgtm, size/S

#1600 Simplify reading the digest file obtained when pulling a Docker image
  container/pull.bzl
Labels: approved, cla: yes, lgtm, size/XS

#1596 Update shas
  container/archive.py
  container/image_test.py
  tests/container/BUILD
Labels: approved, cla: yes, lgtm, size/L

#1598 Add Linux ARM64 go pusher and loader binaries to cloudbuild
  container/go/cloudbuild.yaml
Labels: approved, cla: yes, lgtm, size/M

#1605 Revert "Add Linux ARM64 go pusher and loader binaries to cloudbuild (…
  container/go/cloudbuild.yaml
Labels: approved, cla: yes, lgtm, size/M

#1608 Update puller and loader locations and sequencing in cloudbuild
  container/go/cloudbuild.yaml
Labels: approved, cla: yes, lgtm, size/M
