Repository bazelbuild/rules_docker, pull requests merged in 2021-03, with the labels that each got.

#1750 Invite maintainers from community
  CODEOWNERS
  OWNERS
  README.md
Labels: approved, cla: yes, size/S

#1739 Add Domino Data Lab to list of adopters
  README.md
Labels: cla: yes, lgtm, size/XS

#1753 Revert "Invite maintainers from community (#1750)"
  .github/CODEOWNERS
  CODEOWNERS
  README.md
Labels: cla: yes, size/S

#1754 Add issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes, size/L

#1755 Remove warning about go_image on Mac
  README.md
Labels: cla: yes, size/XS

#1757 Introduce github action to mark stale issues/PRs
  .github/workflows/stale.yml
Labels: cla: yes, size/M

#1762 Setup assign-size-label action
  .github/workflows/size-label.yml
Labels: cla: yes

#1730 Propagate tags to the container image test bundle
  contrib/test.bzl
Labels: cla: yes, lgtm, size/XS

#1770 update_deps: Correctly check if manifest pull failed
  cc/cc.bzl
  container/go/cmd/update_deps/update_deps.go
  go/go.bzl
  go/static.bzl
  java/java.bzl
  java/jetty.bzl
  nodejs/nodejs.bzl
  python/python.bzl
  python3/python3.bzl
Labels: cla: yes, size/M

#1767 Remove google cloud build integration
  cloudbuild.yaml
Labels: cla: yes

#1781 Revert "Remove google cloud build integration (#1767)"
  cloudbuild.yaml
Labels: cla: yes, size/S

#1786 Revert "Setup assign-size-label action"
  .github/workflows/size-label.yml
Labels: cla: yes

#1797 fix the build
  WORKSPACE
Labels: cla: yes
