Repository bazelbuild/rules_docker, pull requests merged in 2021-02, with the labels that each got.

#1723 Fix tests resulting from pip dropping support for legacy Python
  testing/examples/run_instruction_arbitrary/BUILD
  testing/examples/run_instruction_arbitrary/Dockerfile
Labels: approved, cla: yes, lgtm, size/S

#1721 Support computing the digest when caller can only specify --tarball.
  container/go/cmd/digester/digester.go
  container/go/pkg/compat/reader.go
Labels: approved, cla: yes, do-not-merge/hold, size/S

#1720 Renamed `io_bazel_rules_rust` to `rules_rust`
  README.md
  WORKSPACE
  rust/image.bzl
Labels: approved, cla: yes, lgtm, size/M

#1727 Select the structure_test_executable for the execution platform
  contrib/test.bzl
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/XS
